"""`sources/00_manifest.md` — the generated catalog of current bronze evidence.

See sra6-spec.md §5.1 (format and the archive-exclusion rule), §9 (this is the
first step of the researcher's progressive-disclosure path: read the manifest,
then `grep`, then `show`), and §20 (module contract).

Never hand-edited: the file is regenerated wholesale from what is on disk, so
it cannot drift from the evidence it catalogs.
"""

from __future__ import annotations

from pathlib import Path

import frontmatter

MANIFEST_NAME = "00_manifest.md"

# §5.1's format line, reused verbatim as the table header.
COLUMNS = ("id", "kind", "as_of", "bytes", "one-line contents")

SUMMARY_MAX_CHARS = 100


def _summary(post: frontmatter.Post) -> str:
    """One line describing the document: its frontmatter `title`, else its
    first non-empty body line, truncated to `SUMMARY_MAX_CHARS`.

    Whitespace is collapsed to single spaces: a newline inside a title would
    break the table row in half, and the manifest is the one file every
    researcher reads first.
    """
    title = post.metadata.get("title")
    text = str(title).strip() if title else ""
    if not text:
        text = next((ln.strip() for ln in post.content.splitlines() if ln.strip()), "")
    return " ".join(text.split())[:SUMMARY_MAX_CHARS]


def manifest_rows(ticker_dir: Path) -> list[dict]:
    """Rows for every CURRENT source, sorted `as_of` descending then id.

    Excludes `sources/archive/` (§5.1: the manifest catalogs what is true now;
    listing superseded copies would grow the entry point without adding
    evidence) and excludes the manifest file itself, which lives in `sources/`
    but is generated rather than fetched.

    A source whose frontmatter is missing a field degrades to `""` rather than
    raising — a malformed document should still be visible in the catalog so
    it can be found and fixed, not silently omitted. `validate` (§8.4) is the
    gate that makes it fatal.
    """
    sources_dir = ticker_dir / "sources"
    if not sources_dir.is_dir():
        return []

    rows: list[dict] = []
    for path in sources_dir.glob("*.md"):
        if path.name == MANIFEST_NAME:
            continue
        post = frontmatter.loads(path.read_text(encoding="utf-8"))
        rows.append({
            "id": str(post.metadata.get("id") or path.stem),
            "kind": str(post.metadata.get("kind") or ""),
            "as_of": str(post.metadata.get("as_of") or ""),
            "bytes": path.stat().st_size,
            "summary": _summary(post),
        })

    # Two stable passes rather than one keyed sort: the two columns run in
    # opposite directions (as_of descending, id ascending within a tie), and
    # a single `reverse=True` would flip the id tiebreak too.
    rows.sort(key=lambda r: r["id"])
    rows.sort(key=lambda r: r["as_of"], reverse=True)
    return rows


def _cell(value: object) -> str:
    """Escape a value for a markdown table cell. A raw `|` would split the row
    into phantom columns."""
    return str(value).replace("|", r"\|")


def build_manifest(ticker_dir: Path) -> Path:
    """Regenerate `sources/00_manifest.md` and return its path (§5.1).

    Deterministic: the same evidence on disk always produces byte-identical
    output, so regenerating never shows up as a spurious change.
    """
    rows = manifest_rows(ticker_dir)
    lines = [
        f"# {ticker_dir.name} source manifest",
        "",
        f"Generated by `sra.py manifest {ticker_dir.name}` — never hand-edited.",
        "",
        "| " + " | ".join(COLUMNS) + " |",
        "|" + "|".join("---" for _ in COLUMNS) + "|",
    ]
    lines += [
        "| " + " | ".join(
            _cell(r[k]) for k in ("id", "kind", "as_of", "bytes", "summary")
        ) + " |"
        for r in rows
    ]

    sources_dir = ticker_dir / "sources"
    sources_dir.mkdir(parents=True, exist_ok=True)
    path = sources_dir / MANIFEST_NAME
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
